version: '3.8'

services:
  yzv322e-web-server:
    image: nginx:alpine
    container_name: yzv322e-web-server
    ports:
      - "8080:80"
    restart: always

  yzv322e-redis-cache:
    image: redis:alpine
    container_name: yzv322e-redis-cache
    restart: always

  yzv322e-log-generator:
    image: alpine
    container_name: yzv322e-log-generator
    command: ["/bin/sh", "-c", "while true; do echo \"[INFO] Heartbeat: $$(date)\"; sleep 2; done"]